# Generated by Django 4.2.2 on 2023-08-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cdur',
            field=models.CharField(max_length=20),
        ),
    ]
