# Generated by Django 4.2.2 on 2023-08-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_course_cdur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cprice',
            field=models.CharField(max_length=20),
        ),
    ]
